Farmer/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include('forum.urls')),
    path('', include('pwa.urls')),
    prefix_default_language=False,
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'

urlpatterns = [
    # Outer URLS

    path('government-rules/', views.goverment_rules, name='government_rules'),

    # /login/
    path('login/', views.login, name='login'),

    # /signup/
    # path('signup/', views.signup, name='signup'),

    # /home/
    path('home', views.home, name='home'),

    # /
    path('', views.index, name='index'),


    # /farmer/<int:pk>
    path('farmer/<int:pk>', views.FarmerDetailView.as_view(), name='farmer_detail'),

    # /question/<int:pk>
    path('question/<int:pk>', views.question_detail_view, name='question_detail'),

    # /logout/
    path("logout/", views.logout, name="logout"),

    # create-question/
    # path("create-question/", views.create_question, name="create_question"),

    # specialists/
    path("specialists/", views.specialists, name="specialists"),

    # # edit/
    # path("edit/", views.FarmerUpdateView.as_view(), name="edit_farmer"),

    # search?q=<search_term>
    path("search", views.search, name="search"),

    # AJAX URLS

    # upvote-question/

    path("upvote-question/", views.upvote_question, name="upvote_question"),

    # upvote-answer/
    path("upvote-answer/", views.upvote_answer, name="upvote_answer"),

    path("<int:phone_number>/<str:account_token>/",
         views.verify_farmer, name="verify_farmer"),

    path("team-page/", views.team_page, name="team_page"),

    path("feedback/", views.feedback, name="feedback"),
]

forum/forms.py
from django import forms
from django.forms.utils import ErrorList
from .models import Farmer, Question, Answer
from django.utils.translation import gettext_lazy as _


class PlainErrorList(ErrorList):
    """ Show errors as plain text, instead of unordered list """

    def __str__(self):
        return self.as_plain()

    def as_plain(self):
        if not self:
            return ''

        return '%s' % ''.join(['%s' % e for e in self])


class MaterialForm(forms.Form):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Show errors as plain text, instead of
        # unordered list
        self.error_class = PlainErrorList

        for field_name, field in self.fields.items():

            # if the field is a textarea field
            # then append `materialize-textarea` class to the field

            if isinstance(field.widget, forms.Textarea):

                OLD_CLASS = field.widget.attrs.get('class', "")
                NEW_CLASS = " materialize-textarea"

                field.widget.attrs.update({
                    'class': OLD_CLASS + NEW_CLASS
                })

    def add_error(self, field, error):

        super().add_error(field, error)

        for field_name, field in self.fields.items():
            if self[field_name].errors:

                OLD_CLASS = field.widget.attrs.get('class', "")
                NEW_CLASS = " invalid"

                field.widget.attrs.update(
                    {'class':  OLD_CLASS + NEW_CLASS})


class SignupForm(MaterialForm, forms.ModelForm):

    class Meta:
        model = Farmer
        exclude = ['date_time_created']

        widgets = {
            'phone_number': forms.TextInput(
                attrs={
                    'autofocus': False,
                    'type': 'tel'
                }
            ),
            'password': forms.PasswordInput(
                attrs={
                    'type': 'password'
                }
            ),
            'dob': forms.TextInput(
                attrs={
                    'placeholder': 'YYYY-MM-DD'
                }
            )
        }


class LoginForm(MaterialForm):

    phone_number = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'autofocus': False,
                'type': 'tel'
            }
        ), label=_("Phone number")
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'type': 'password'
            }
        ), label=_("Farmer's password")
    )


class CreateQuestionForm(MaterialForm, forms.ModelForm):

    file_field = forms.FileField(required=False,
                                 widget=forms.FileInput(
                                     attrs={
                                         'accept': 'image/*, video/*'
                                     }
                                 ))

    class Meta:
        model = Question
        fields = ['question', 'category']

        widgets = {
            'question': forms.Textarea(
                attrs={
                    'autofocus': True,
                    'value': ''
                }
            )
        }


class CreateAnswerForm(MaterialForm, forms.ModelForm):

    class Meta:
        model = Answer
        fields = ['answer', ]

        widgets = {
            'answer': forms.Textarea(
                attrs={
                    'autofocus': True,
                    'value': ''
                }
            )
        }


class FarmerEditForm(MaterialForm, forms.ModelForm):

    class Meta:
        model = Farmer
        exclude = ['date_time_created', 'password']

        widgets = {
            'phone_number': forms.Textarea(
                attrs={
                    'autofocus': True
                }
            )
        }

forum/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import (
    get_object_or_404, redirect, render, reverse, Http404
)

from . import forms as custom_forms
from .models import Farmer, Question, Answer, Specialist, QuestionFile
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from django.utils.translation import get_language

from .validators import validate_file_extension, validate_file_size

from django.contrib.auth.hashers import check_password, make_password
from django.views import generic

# Helpers

def language_details(request):
    
    language_code = get_language()

    another_language = {
        'en': 'हिंदी',
        'hi': 'english'
    }[language_code]

    current_url = request.get_full_path()

    url_for_language_change = {
        'hi': '/en' + current_url,
        'en': current_url[3:],
    }[language_code]

    return {
        'another_language': another_language,
        'url_for_language_change': url_for_language_change
    }


def loggined_farmer_id(request):
    """ Gives the id of the currently logged in farmer
        returns `None` if no farmer is logged in
    """

    return request.session.get("farmer_id", None)


def loggined_farmer(request):
    return get_object_or_404(
        Farmer,
        pk=loggined_farmer_id(request)
    )


def is_loggined(request):

    try:
        farmer_id = request.session.get("farmer_id")
        Farmer.objects.get(id=farmer_id)
        return True

    except Farmer.DoesNotExist:
        return False


def login_required(function):

    def wrapper(request, *args, **kwargs):

        if is_loggined(request):
            return function(request, *args, **kwargs)

        return redirect("forum:login")

    return wrapper


def basic_inner_context(request):
    """Basic context for inner views """

    farmer = loggined_farmer(request)
    top_questions = Question.trending()

    return {
        'farmer': farmer,
        'top_questions': top_questions,
        **language_details(request),
    }

# Create your views here.
# Views start here


def login(request, verify_message=""):

    login_form = custom_forms.LoginForm()

    if request.method == "POST":

        login_form = custom_forms.LoginForm(request.POST)

        if login_form.is_valid():

            phone_number = login_form.cleaned_data['phone_number']
            password = login_form.cleaned_data['password']

            try:
                farmer = Farmer.objects.get(phone_number=phone_number)

                if check_password(password, farmer.password):

                    # if not farmer.is_active:
                    #     login_form.add_error('phone_number', _(
                    #         "Account is not activated"))

                    # else:
                    request.session['farmer_id'] = farmer.id
                    return redirect("forum:home")

                if farmer.is_active:
                    login_form.add_error('password', _("Invalid password"))

            except Farmer.DoesNotExist:
                login_form.add_error('phone_number', _(
                    "No Farmer found with this phone number"))

    return render(request, "forum/outer/login.html", {
        'form': login_form,
        'verify_message': verify_message,
        **language_details(request),
    })


# def signup(request):

#     signup_form = custom_forms.SignupForm()

#     is_message_send = False

#     if request.method == "POST":

#         signup_form = custom_forms.SignupForm(request.POST)

#         if signup_form.is_valid():

#             new_farmer = signup_form.save()

#             password = make_password(signup_form.cleaned_data['password'])
#             new_farmer.password = password

#             new_farmer.save()

#             # verification message send
#             new_farmer.send_verification_link()
#             is_message_send = True

#     return render(request, "forum/outer/signup.html", {
#         'form': signup_form,
#         'is_message_send': is_message_send,
#         **language_details(request),

#     })


def goverment_rules(request):

    rules = [
        {
            'name': _("Rastriya Krishi Vikas Yojna (RKVY)"),
            'description': _("It is implemented with a view to promote organic farming in the country. To improve soil health and organic matter content and increase net income of the farmer so as to realise premium prices.  Under this scheme, an area of 5 lakh acre is targeted to be covered though 10,000 clusters of 50 acre each, from the year 2015-16 to 2017-18."),
            'link': 'http://agriportal.cg.nic.in/agridept/AgriEn/CentralScheme.html#collapseFive'
        },
        {
            'name': _("Crop Insurance"),
            'description': _("Crop insurance is purchased by agricultural producers, and subsidized by the federal government, to protect against either the loss of their crops due to natural disasters, such as hail, drought, and floods, or the loss of revenue due to declines in the prices of agricultural commodities."),
            'link': 'http://agriportal.cg.nic.in/agridept/AgriEn/CentralScheme.html#collapseOne'
        },
        {
            'name': _("National Mission on Sustainable Agriculture (NMSA)"),
            'description': _("NMSA is one of the eight Missions under National Action Plan on Climate Change (NAPCC). It aims at promoting Sustainable Agriculture through climate change adaptation measures, enhancing agriculture productivity especially in rainfed areas focusing on integrated farming, soil health management, and synergizing resource conservation. NMSA as a programmatic intervention caters to Mission Deliverables that focuses mainly on conservation agriculture to make farm sector more productive, sustainable, remunerative and climate resilient by promoting location specific integrated/composite farming systems."),
            'link': 'http://agriportal.cg.nic.in/agridept/AgriEn/CentralScheme.html#collapseOne'
        },
        {
            'name': _("National Food Security Mission (NFSM)"),
            'description': _("In view of the stagnating food grain production and an increasing consumption need of the growing population, Government of India has launched this Centrally Sponsored Scheme, ‘National Food Security Mission’ in October 2007. The Mission met with an overwhelming success and achieved the targeted additional production of rice, wheat and pulses. The Mission continued during 12th Five Year Plan with new targets of additional production of food grains of 25 million tonnes of food grains comprising of 10 million tonnes rice, 8 million tonnes of wheat, 4 million tonnes of pulses and 3 million tonnes of coarse cereals by the end of 12th Five Year Plan."),
            'link': 'http://agriportal.cg.nic.in/agridept/AgriEn/CentralScheme.html#collapseOne'
        },
        {
            'name': _("National Mission on Agriculture Extension & Technology (NMAET)"),
            'description': _("The objective of the Scheme is to make the extension system farmer-driven and farmer-accountable by way of new institutional arrangements for technology dissemination. It aims to restructure and strengthen agricultural extension to enable delivery of appropriate technology and improved agronomic practices to farmers."),
            'link': 'http://agriportal.cg.nic.in/agridept/AgriEn/CentralScheme.html#collapseOne'
        }
    ]

    return render(request, "forum/outer/govt_rules.html", {
        "rules": rules,
        **language_details(request),
    })


def index(request):

    # Show home if loggined

    if is_loggined(request):
        return home(request)

    # else show login page
    return login(request)


@login_required
def home(request):

    current_farmer = loggined_farmer(request)

    DEFAULT_CHOICE = 'all'
    categories = [DEFAULT_CHOICE, 'AN', 'PE', 'SU', 'SE', 'SA']
    category = request.GET.get("category")

    if category not in categories:
        category = DEFAULT_CHOICE

    all_questions = Question.objects.all()

    questions_from_nearby_farmers = (
        current_farmer.questions_from_nearby_farmers()
    )

    questions = {
        DEFAULT_CHOICE: all_questions,
        'AN': all_questions.filter(category='AN'),
        'PE': all_questions.filter(category='PE'),
        'SU': all_questions.filter(category='SU'),
        'SE': all_questions.filter(category='SE'),
        'SA': questions_from_nearby_farmers
    }[category]

    category_name = Question.full_category_name(category, _("All"))

    return render(request, "forum/inner/home.html", {
        **basic_inner_context(request),
        'questions': questions.order_by("-date_time_created"),
        'category': category,
        'category_name': category_name,
        'show_filter': True
    })


# def create_question(request):

#     FILE_LIMIT = 10
#     error_occured = False

#     create_form = custom_forms.CreateQuestionForm()

#     if request.method == "POST":

#         create_form = custom_forms.CreateQuestionForm(request.POST)
#         files = request.FILES.getlist('file_field')

#         if create_form.is_valid():

#             question = create_form.save(commit=False)
#             question.asked_by = loggined_farmer(request)
#             question.save()

#             if len(files) > FILE_LIMIT:
#                 create_form.add_error('file_field', _(
#                     "Upto 10 files can be attached with a question"))
#                 error_occured = True

#             for f in files:

#                 try:
#                     validate_file_extension(f)
#                     validate_file_size(f)

#                     question_file = QuestionFile.objects.create()
#                     question_file.save()

#                     question_file.question_file = f
#                     question_file.save()

#                     question.files.add(question_file)

forum/templates/forum/outer/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#1565c0" />
  <meta name="Description" content="{% trans "Solutions for farmers by farmers !" %}">
  <link rel="icon" href="{% static 'forum/images/icons/icon-144x144.png' %}">

  <title>
    {% block title %}{% endblock title %} - {% trans "Kisan" %}
  </title>


  {% block resource %}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'forum/css/main.css' %}">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

  {% endblock resource %}


</head>

<body>

  <!--Navbar-->
  <div class="navbar-fixed">
    <nav class="blue darken-3">
      <div class="container">
        <div class="nav-wrapper">
          <a href="{% url 'forum:index' %}" class="brand-logo logo-custom">
            <b> {% trans "Kisan" %} </b>
          </a>

          <a href="#" data-target="farmer-options" class="sidenav-trigger"><i class="material-icons">menu</i></a>

          

          <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'forum:login' %}"> {% trans "Login" %} </a></li>
            <li><a href="{% url 'forum:government_rules' %}"> {% trans "Government rules" %} </a></li>
            <li>
              <a href="{% url 'forum:team_page' %}"> {% trans "Team" %} </a>
              <!-- Dropdown Trigger -->
      <!-- <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">{% trans "Language" %}<i class="material-icons right">arrow_drop_down</i></a></li> -->
            </li>
            <li> <a href=" {% url 'forum:feedback' %} "> {% trans "Give Feedback" %} </a> </li>
          </ul>

        </div>
      </div>
    </nav>
  </div>

  <ul class="sidenav" id="farmer-options">
    <li><a href="{% url 'forum:login' %}"> {% trans "Login" %} </a></li>
    <li><a href="{% url 'forum:government_rules' %}"> {% trans "Government rules" %} </a></li>
    <li>
        <a href="{% url 'forum:team_page' %}"> {% trans "Team" %} </a>
    </li>
    <li> <a href=" {% url 'forum:feedback' %} "> {% trans "Give Feedback" %} </a> </li>
  </ul>

  {% block main %}

  <!-- Section:Slider -->
  

      <section class="slider">
        <div class="slider">
          <ul class="slides">
            <li>
              <img src="{% static 'forum/images/1.webp' %}" alt="">
              <div class="caption left-align">
                <h2 class="light white-text">{% trans "Solutions for farmers by farmers !" %}</h2>
            </li>
            <li>
              <img src="{% static 'forum/images/2.webp' %}" alt="">
              <div class="caption center-align">
                <h2 class="light white-text">{% trans "Solutions for farmers by farmers !" %}</h2>
            </li>
            <li>
              <img src="{% static 'forum/images/3.webp' %}" alt="">
              <div class="caption right-align">
                <h2 class="light white-text"> {% trans "Solutions for farmers by farmers !" %} </h2>
            </li>
          </ul>
        </div>
      </section>

      <!-- Section-signup -->



      <section class="section section-signup">
        <div class="container">

          <div class="row">
            
            <div class="col s12 m6">
              {% block content %}{% endblock content %}
            </div>

            <div class="col s12 m6">
              <h5> {% trans "Get a free account" %} </h5>
              <p style="text-align:justify" class="flow-text grey-text text-darken-3">
                {% trans "Our objective is to keep farmers in tune with the latest developments in relevant technologies, and to harness these emerging opportunities in transforming their lives. Indian farmers rely on each other for guidance on the type of seeds to use, diagnosis of pests and diseases as well as their remedies. In the ideal situation farmers will be able to login to see information that other farmers have inputted." %}
              </p>
            </div>

          </div>

        
        </div>
      </section>

  {% endblock main %}



  {% comment %} Footer {% endcomment %}
  <footer class="page-footer blue darken-3">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text"> {% trans "Kisan" %} </h5>
          <p class="grey-text text-lighten-4">
            {% trans "Our objective is to keep farmers in tune with the latest developments in relevant technologies, and to harness these emerging opportunities in transforming their lives. Indian farmers rely on each other for guidance on the type of seeds to use, diagnosis of pests and diseases as well as their remedies. In the ideal situation farmers will be able to login to see information that other farmers have inputted." %}
          </p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text"> {% trans "Learn more" %} </h5>
          <ul>
            <li><a class="grey-text text-lighten-3" href="{% url 'forum:login' %}"> {% trans "Login" %} </a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
        © {% now "Y" %} {% trans "Kisan" %}
        <a class="right btn white blue-text" href="{{url_for_language_change}}"> {{another_language}}  </a>
      </div>
    </div>
  </footer>

</body>

{% block JS %}
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"
  type="text/javascript"></script>
<script src="{% static 'forum/js/main.js' %}" type="text/javascript"></script>

{% endblock JS %}

</html>

forum/templates/forum/outer/feedback.html
{% extends 'forum/outer/base.html' %}
{% load i18n %}

{% block title %}{% trans "Give Feedback" %}{% endblock title %}



{% block main %}
<div class="row"></div>
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdKq-nhAvfgNUP8m96bVZEVvHognuKEnRvs9-KPZ1GTEHpyvg/viewform?embedded=true" width="100%" height="1172" frameborder="0" marginheight="0" marginwidth="0">लोड हो रहा है...</iframe>


{% endblock main %}

forum/templates/forum/outer/govt_rules.html
{% extends 'forum/outer/base.html' %}
{% load i18n %}

{% block title %} {% trans "Government rules" %} {% endblock title %}


{% block content %}


    <h4 class="custom-font"> {% trans "Programs and Schemes" %}</h4>

    <div class="container">
        <div class="row"></div>
    </div>


    <div class="card">
        <div class="card-content">
          <span class="card-title blue-text text-darken-4 custom-font">राष्ट्रीय कृषि विकास योजना (रकव्य)</span>
          <p>
            इसे देश में जैविक खेती को बढ़ावा देने के उद्देश्य से लागू किया गया है। मृदा स्वास्थ्य और जैविक पदार्थ की मात्रा में सुधार करना और किसान की शुद्ध आय में वृद्धि करना ताकि प्रीमियम कीमतों का एहसास हो सके। इस योजना के तहत, 5 लाख एकड़ के क्षेत्र को कवर करने का लक्ष्य रखा गया है, जबकि वर्ष 2015-16 से 2017-18 तक प्रत्येक में 50 एकड़ के 10,000 क्लस्टर शामिल हैं।
          </p>
        </div>
        <div class="card-action right-align">
          <a href="http://agriportal.cg.nic.in/agridept/AgriEn/CentralScheme.html#collapseFive" class="btn blue darken-3 no-underline waves-effect" >learn more</a>
        </div>
    </div>

    <div class="card">
        <div class="card-content">
          <span class="card-title blue-text text-darken-4 custom-font">फसल बीमा</span>
          <p>
            कृषि उत्पादकों द्वारा फसल बीमा खरीदा जाता है, और प्राकृतिक आपदाओं, जैसे ओलावृष्टि, सूखा और बाढ़ के कारण उनकी फसलों के नुकसान से बचाने के लिए या संघीय सरकार द्वारा सब्सिडी दी जाती है, या कीमतों में गिरावट के कारण राजस्व का नुकसान होता है। कृषि माल।
          </p>
        </div>
        <div class="card-action right-align">
          <a href="http://agriportal.cg.nic.in/agridept/AgriEn/CentralScheme.html#collapseOne" class="btn blue darken-3 no-underline waves-effect" >learn more</a>
        </div>
    </div>

    <div class="card">
        <div class="card-content">
          <span class="card-title blue-text text-darken-4 custom-font">सतत कृषि पर राष्ट्रीय मिशन (NMSA)</span>
          <p>
            एनएमएसए नेशनल एक्शन प्लान ऑन क्लाइमेट चेंज (एनएपीसीसी) के तहत आठ मिशनों में से एक है। इसका उद्देश्य जलवायु परिवर्तन अनुकूलन उपायों के माध्यम से सतत कृषि को बढ़ावा देना है, विशेष रूप से वर्षा आधारित क्षेत्रों में कृषि उत्पादकता को बढ़ाना, एकीकृत खेती, मृदा स्वास्थ्य प्रबंधन और संसाधन संरक्षण पर जोर देना।
                            NMSA एक प्रोग्रामेटिक हस्तक्षेप के रूप में मिशन डेलीवेबल्स को पूरा करता है जो मुख्य रूप से एकीकृत क्षेत्र / एकीकृत कृषि प्रणालियों को बढ़ावा देकर कृषि क्षेत्र को अधिक उत्पादक, टिकाऊ, पारिश्रमिक और जलवायु लचीला बनाने के लिए संरक्षण कृषि पर केंद्रित है। 
          </p>
        </div>
        <div class="card-action right-align">
          <a href="http://agriportal.cg.nic.in/agridept/AgriEn/CentralScheme.html#collapseOne" class="btn blue darken-3 no-underline waves-effect" >learn more</a>
        </div>
    </div>

    <div class="card">
        <div class="card-content">
          <span class="card-title blue-text text-darken-4 custom-font">राष्ट्रीय खाद्य सुरक्षा मिशन (NFSM)</span>
          <p>
            बढ़ती खाद्यान्न उत्पादन और बढ़ती जनसंख्या की बढ़ती खपत की जरूरतों के मद्देनजर, भारत सरकार ने अक्टूबर 2007 में इस केंद्र प्रायोजित योजना, Scheme राष्ट्रीय खाद्य सुरक्षा मिशन ’की शुरुआत की।
                              िशन ने भारी सफलता के साथ मुलाकात की और चावल, गेहूं और दालों के लक्षित अतिरिक्त उत्पादन को प्राप्त किया। मिशन 10                              मिलियन टन चावल, 8 मिलियन टन गेहूं, 4 मिलियन टन दालों और 3 मिलियन टन मोटे अनाज के 25 मिलियन टन खाद्यान्न के                                    अतिरिक्त उत्पादन के नए लक्ष्य के साथ 12 वीं पंचवर्षीय योजना के दौरान जारी रहा। 12 वीं पंचवर्षीय योजना का अंत।
          </p>
        </div>
        <div class="card-action right-align">
          <a href="http://agriportal.cg.nic.in/agridept/AgriEn/CentralScheme.html#collapseOne" class="btn blue darken-3 no-underline waves-effect" >learn more</a>
          
        </div>
    </div>

    <div class="card">
        <div class="card-content">
          <span class="card-title blue-text text-darken-4 custom-font">तिलहन और तेल फार्म पर राष्ट्रीय मिशन (NMOOP)</span>
          <p>
            भारत प्रमुख तिलहन उत्पादकों में से एक है और खाद्य तेलों का आयातक है। संयुक्त राज्य अमेरिका, चीन और ब्राजील के बाद भारत की वनस्पति तेल अर्थव्यवस्था दुनिया की चौथी सबसे बड़ी है। तिलहन का सकल फसल क्षेत्र का 13%, सकल राष्ट्रीय उत्पाद का 3% और सभी कृषि वस्तुओं का 10% मूल्य है। इस क्षेत्र ने पिछले दशक (1999-2009) के दौरान क्रमशः क्षेत्र, उत्पादन और उपज की वार्षिक वृद्धि दर 2.44%, 5.47% और 2.96% दर्ज की है।
          </p>
        </div>
        <div class="card-action right-align">
          <a href="http://agriportal.cg.nic.in/agridept/AgriEn/CentralScheme.html#collapseOne" class="btn blue darken-3 no-underline waves-effect" >learn more</a>
        </div>
    </div>

    <div class="card">
        <div class="card-content">
          <span class="card-title blue-text text-darken-4 custom-font">कृषि विस्तार और प्रौद्योगिकी पर राष्ट्रीय मिशन (NMAET)</span>
          <p>
            योजना का उद्देश्य प्रौद्योगिकी प्रसार के लिए नई संस्थागत व्यवस्था के माध्यम से विस्तार प्रणाली को किसान-संचालित और किसान-जवाबदेह बनाना है। इसका उद्देश्य किसानों को उपयुक्त प्रौद्योगिकी के वितरण और कृषि संबंधी कृषि पद्धतियों को बेहतर बनाने के लिए कृषि विस्तार का पुनर्गठन और सुदृढ़ीकरण करना है।
          </p>
        </div>
        <div class="card-action right-align">
          <a href="http://agriportal.cg.nic.in/agridept/AgriEn/CentralScheme.html#collapseOne" class="btn blue darken-3 no-underline waves-effect" >learn more</a>
        </div>
    </div>

{% endblock content %}

forum/templates/forum/outer/login.html
{% extends 'forum/outer/base.html' %}
{% load i18n %}

{% block title %} {% trans "Login" %} {% endblock title %}


{% block content %}

    <div class="card-panel grey lighten-4 grey-text z-depth-0 text-darken-4">

        <h5 class="row center"> {% trans "Login" %} </h5>

        <form method="POST">
                {% csrf_token %}
                <div class="input-field">
                    {{form.phone_number.label_tag}}
                    {{form.phone_number}}
                    <span class="helper-text" data-error="{{form.phone_number.errors}}"></span>
                </div>
                    
                <div class="input-field">
                    {{form.password.label_tag}}
                    {{form.password}}
                    <span class="helper-text" data-error="{{form.password.errors}}"></span>
                </div>

            <div class="center-align">
                <button type="submit" class="btn blue darken-3"> {% trans "Login" %} </button>
            </div>
        </form>

    </div>

{% endblock content %}